title: Kartheek Akella
url: "https://asvskartheek.github.io"
baseurl: "/"

markdown: kramdown

tracking_id: #

footer: yes
footer_url: "https://github.com/asvskartheek"
footer_text: "Kartheek Akella (c) 2020-2021"

sass:
    style: compressed
    sass_dir: _sass

include: ["_includes"]